name: Build and Release

on:
  push:
    tags:
      - "v*" # This triggers the workflow when a tag starting with 'v' is pushed (e.g., v1.0.0).

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2" # Replace with your Go version if different

      - name: Build binary
        run: |
          go build -o wrought .

      - name: Archive binary
        run: tar -czvf wrought.tar.gz wrought # Compress the binary for release

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: wrought-binary
          path: wrought.tar.gz

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20" # Use the same Go version as in the build job

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }} # Uses the pushed tag as the release version
          release_name: Release ${{ github.ref }}
          body: |
            Release notes for version ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically provided by GitHub

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wrought.tar.gz # Path to the binary from the build step
          asset_name: wrought.tar.gz
          asset_content_type: application/gzip
